export const MONITOR_SYMBOLS = [
  // Financials (20)
  'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'KOTAKBANK.NS', 'AXISBANK.NS',
  'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 'LICHSGFIN.NS',
  'PFC.NS', 'RECLTD.NS', 'MUTHOOTFIN.NS', 'CHOLAFIN.NS', 'SHRIRAMFIN.NS',
  'BANDHANBNK.NS', 'IDFCFIRSTB.NS', 'INDUSINDBK.NS', 'PNB.NS', 'BOB.NS',

  // IT (20)
  'TCS.NS', 'INFY.NS', 'WIPRO.NS', 'HCLTECH.NS', 'TECHM.NS',
  'HAPPSTMNDS.NS', 'LTTS.NS', 'PERSISTENT.NS', 'COFORGE.NS', 'MPHASIS.NS',
  'KPITTECH.NS', 'TATAELXSI.NS', 'CYIENT.NS', 'SONATSOFTW.NS', 'ZENSARTECH.NS',
  'OFSS.NS', 'BSOFT.NS', 'NAUKRI.NS', 'AFFLE.NS', 'FSL.NS',

  // Staples (20)
  'HINDUNILVR.NS', 'ITC.NS', 'NESTLEIND.NS', 'BRITANNIA.NS', 'DABUR.NS',
  'GODREJCP.NS', 'COLPAL.NS', 'MARICO.NS', 'TATACONSUM.NS', 'VBL.NS',
  'UBL.NS', 'UNITDSPR.NS', 'BALRAMCHIN.NS', 'KRBL.NS', 'LTFOODS.NS',
  'HERITGFOOD.NS', 'AVANTIFEED.NS', 'EMAMILTD.NS', 'JYOTHYLAB.NS', 'HATSUN.NS',

  // Discretionary (20)
  'MARUTI.NS', 'TMPV.NS', 'TMCV.NS', 'M&M.NS', 'EICHERMOT.NS',
  'HEROMOTOCO.NS', 'BAJAJ-AUTO.NS', 'TITAN.NS', 'TRENT.NS', 'DMART.NS',
  'PAGEIND.NS', 'BATAINDIA.NS', 'RELAXO.NS', 'KALYANKJIL.NS', 'ABFRL.NS',
  'DEVYANI.NS', 'JUBLFOOD.NS', 'WESTLIFE.NS', 'VIPIND.NS', 'RAYMOND.NS',

  // Energy (20)
  'RELIANCE.NS', 'ONGC.NS', 'IOC.NS', 'BPCL.NS', 'HPCL.NS',
  'OIL.NS', 'COALINDIA.NS', 'ADANIGREEN.NS', 'ADANIENSOL.NS', 'MRPL.NS',
  'CHENNPETRO.NS', 'PETRONET.NS', 'GSPL.NS', 'GAIL.NS', 'MGL.NS',
  'IGL.NS', 'PANAMAPET.NS', 'ATGL.NS', 'CASTROLIND.NS', 'AEGISLOG.NS',

  // Industrials (20)
  'LT.NS', 'RVNL.NS', 'BHEL.NS', 'IRCTC.NS', 'IRFC.NS',
  'CONCOR.NS', 'BEL.NS', 'HAL.NS', 'GMRAIRPORT.NS', 'IRCON.NS',
  'HEG.NS', 'GRAPHITE.NS', 'CUMMINSIND.NS', 'ABB.NS', 'SIEMENS.NS',
  'THERMAX.NS', 'VOLTAS.NS', 'BLUESTARCO.NS', 'KEC.NS', 'ENGINERSIN.NS',

  // Materials (20)
  'TATASTEEL.NS', 'JSWSTEEL.NS', 'HINDALCO.NS', 'GRASIM.NS', 'AMBUJACEM.NS',
  'ULTRACEMCO.NS', 'ACC.NS', 'SHREECEM.NS', 'JKCEMENT.NS', 'RAMCOCEM.NS',
  'SAIL.NS', 'JINDALSTEL.NS', 'NMDC.NS', 'NATIONALUM.NS', 'ASIANPAINT.NS',
  'BERGEPAINT.NS', 'KANSAINER.NS', 'PIDILITIND.NS', 'SRF.NS', 'DEEPAKNTR.NS',

  // Health Care (20)
  'SUNPHARMA.NS', 'CIPLA.NS', 'DIVISLAB.NS', 'APOLLOHOSP.NS', 'DRREDDY.NS',
  'LUPIN.NS', 'AUROPHARMA.NS', 'BIOCON.NS', 'GLAND.NS', 'IPCALAB.NS',
  'LAURUSLABS.NS', 'MAXHEALTH.NS', 'FORTIS.NS', 'SYNGENE.NS', 'METROPOLIS.NS',
  'LALPATHLAB.NS', 'TORNTPHARM.NS', 'ALKEM.NS', 'ZYDUSLIFE.NS', 'GLAXO.NS',

  // Communication (20)
  'BHARTIARTL.NS', 'IDEA.NS', 'TATACOMM.NS', 'ZEEL.NS', 'SUNTV.NS',
  'PVRINOX.NS', 'NETWORK18.NS', 'HATHWAY.NS', 'DEN.NS', 'SAREGAMA.NS',
  'TIPSMUSIC.NS', 'DISHTV.NS', 'MTNL.NS', 'ROUTE.NS', 'TANLA.NS',
  'ZEEMEDIA.NS', 'DBCORP.NS', 'JAGRAN.NS', 'ENIL.NS', 'TVTODAY.NS',

  // Utilities (20)
  'NTPC.NS', 'TATAPOWER.NS', 'POWERGRID.NS', 'ADANIPOWER.NS', 'TORNTPOWER.NS',
  'CESC.NS', 'NLCINDIA.NS', 'JPPOWER.NS', 'RTNPOWER.NS', 'GIPCL.NS',
  'SJVN.NS', 'NHPC.NS', 'WABAG.NS', 'JSWENERGY.NS', 'KPIGREEN.NS',
  'PTC.NS', 'GUJGASLTD.NS', 'GENUSPOWER.NS', 'SWSOLAR.NS', 'BFUTILITIE.NS'
];

export const LARGE_CAP_SYMBOLS = [
  'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'KOTAKBANK.NS', 'AXISBANK.NS',
  'BAJFINANCE.NS', 'BAJAJFINSV.NS', 'HDFCLIFE.NS', 'SBILIFE.NS', 'SHRIRAMFIN.NS',
  'TCS.NS', 'INFY.NS', 'WIPRO.NS', 'HCLTECH.NS', 'TECHM.NS', 'OFSS.NS',
  'HINDUNILVR.NS', 'ITC.NS', 'NESTLEIND.NS', 'BRITANNIA.NS', 'VBL.NS',
  'TATACONSUM.NS', 'GODREJCP.NS', 'MARUTI.NS', 'M&M.NS', 'TITAN.NS',
  'TRENT.NS', 'DMART.NS', 'EICHERMOT.NS', 'HEROMOTOCO.NS', 'BAJAJ-AUTO.NS',
  'RELIANCE.NS', 'ONGC.NS', 'IOC.NS', 'BPCL.NS', 'HPCL.NS', 'COALINDIA.NS',
  'ADANIGREEN.NS', 'ADANIENSOL.NS', 'ATGL.NS', 'LT.NS', 'BEL.NS', 'HAL.NS',
  'CONCOR.NS', 'ABB.NS', 'SIEMENS.NS', 'TATASTEEL.NS', 'JSWSTEEL.NS',
  'HINDALCO.NS', 'GRASIM.NS', 'ULTRACEMCO.NS', 'ASIANPAINT.NS', 'PIDILITIND.NS',
  'SHREECEM.NS', 'SUNPHARMA.NS', 'DRREDDY.NS', 'CIPLA.NS', 'DIVISLAB.NS',
  'APOLLOHOSP.NS', 'MAXHEALTH.NS', 'TORNTPHARM.NS', 'BHARTIARTL.NS', 'TATACOMM.NS',
  'NTPC.NS', 'POWERGRID.NS', 'TATAPOWER.NS', 'ADANIPOWER.NS', 'TORNTPOWER.NS',
  'JSWENERGY.NS', 'SWSOLAR.NS', 'CGPOWER.NS', 'GET&D.NS', 'POWERINDIA.NS'
];

export const MID_CAP_SYMBOLS = [
  'PFC.NS', 'RECLTD.NS', 'MUTHOOTFIN.NS', 'CHOLAFIN.NS', 'BANDHANBNK.NS',
  'INDUSINDBK.NS', 'PNB.NS', 'BOB.NS', 'LTTS.NS', 'PERSISTENT.NS',
  'COFORGE.NS', 'MPHASIS.NS', 'KPITTECH.NS', 'TATAELXSI.NS', 'BSOFT.NS',
  'NAUKRI.NS', 'DABUR.NS', 'MARICO.NS', 'COLPAL.NS', 'UBL.NS', 'UNITDSPR.NS',
  'EMAMILTD.NS', 'TMPV.NS', 'TMCV.NS', 'PAGEIND.NS', 'BATAINDIA.NS',
  'KALYANKJIL.NS', 'ABFRL.NS', 'JUBLFOOD.NS', 'OIL.NS', 'MRPL.NS',
  'PETRONET.NS', 'GSPL.NS', 'GAIL.NS', 'MGL.NS', 'IGL.NS', 'RVNL.NS',
  'BHEL.NS', 'IRCTC.NS', 'IRFC.NS', 'CUMMINSIND.NS', 'VOLTAS.NS',
  'GMRAIRPORT.NS', 'AMBUJACEM.NS', 'ACC.NS', 'JKCEMENT.NS', 'RAMCOCEM.NS',
  'SAIL.NS', 'JINDALSTEL.NS', 'NMDC.NS', 'SRF.NS', 'DEEPAKNTR.NS',
  'LUPIN.NS', 'AUROPHARMA.NS', 'BIOCON.NS', 'IPCALAB.NS', 'FORTIS.NS',
  'SYNGENE.NS', 'ZYDUSLIFE.NS', 'ALKEM.NS', 'IDEA.NS', 'ZEEL.NS',
  'SUNTV.NS', 'PVRINOX.NS', 'NETWORK18.NS', 'ROUTE.NS', 'TANLA.NS',
  'CESC.NS', 'NLCINDIA.NS', 'KPIGREEN.NS'
];

export const SMALL_CAP_SYMBOLS = [
  'LICHSGFIN.NS', 'IDFCFIRSTB.NS', 'CYIENT.NS', 'SONATSOFTW.NS', 'ZENSARTECH.NS',
  'AFFLE.NS', 'FSL.NS', 'HAPPSTMNDS.NS', 'BALRAMCHIN.NS', 'KRBL.NS',
  'LTFOODS.NS', 'HERITGFOOD.NS', 'AVANTIFEED.NS', 'JYOTHYLAB.NS', 'HATSUN.NS',
  'RELAXO.NS', 'DEVYANI.NS', 'WESTLIFE.NS', 'VIPIND.NS', 'RAYMOND.NS',
  'CHENNPETRO.NS', 'CASTROLIND.NS', 'AEGISLOG.NS', 'PANAMAPET.NS', 'IRCON.NS',
  'HEG.NS', 'GRAPHITE.NS', 'THERMAX.NS', 'BLUESTARCO.NS', 'KEC.NS',
  'ENGINERSIN.NS', 'NATIONALUM.NS', 'BERGEPAINT.NS', 'KANSAINER.NS', 'GLAND.NS',
  'LAURUSLABS.NS', 'METROPOLIS.NS', 'LALPATHLAB.NS', 'GLAXO.NS', 'HATHWAY.NS',
  'DEN.NS', 'SAREGAMA.NS', 'TIPSMUSIC.NS', 'DISHTV.NS', 'MTNL.NS',
  'ZEEMEDIA.NS', 'DBCORP.NS', 'JAGRAN.NS', 'ENIL.NS', 'TVTODAY.NS',
  'JPPOWER.NS', 'RTNPOWER.NS', 'GIPCL.NS', 'SJVN.NS', 'NHPC.NS',
  'WABAG.NS', 'PTC.NS', 'GUJGASLTD.NS', 'GENUSPOWER.NS', 'BFUTILITIE.NS'
];

export const TRENDING_SYMBOLS = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'TRENT.NS', 'HDFCBANK.NS', 'SBIN.NS', 'TMPV.NS', 'TMCV.NS', 'HAL.NS', 'VEDL.NS'];
export const MOST_SEARCHED_SYMBOLS = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'TRENT.NS', 'IRCTC.NS', 'RVNL.NS', 'SUNPHARMA.NS'];

// Tickertape-style Curated Collections
export const BLUE_CHIP_SYMBOLS = ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS', 'ICICIBANK.NS', 'SBIN.NS', 'LT.NS', 'ITC.NS', 'HINDUNILVR.NS', 'KOTAKBANK.NS'];
export const HIGH_GROWTH_SYMBOLS = ['TRENT.NS', 'HAL.NS', 'RVNL.NS', 'MARUTI.NS', 'M&M.NS', 'KPIGREEN.NS'];
export const DIVIDEND_SYMBOLS = ['IOC.NS', 'BPCL.NS', 'ONGC.NS', 'POWERGRID.NS', 'ITC.NS', 'TATASTEEL.NS'];
export const DEBT_FREE_SYMBOLS = ['TCS.NS', 'INFY.NS', 'WIPRO.NS', 'HCLTECH.NS', 'ITC.NS', 'NESTLEIND.NS', 'DIVISLAB.NS'];
